pool:
  name: Azure Pipelines
  vmImage: 'ubuntu-latest'
steps:
- task: UsePythonVersion@0
  displayName: 'Use Python 3.9'
  inputs:
    versionSpec: 3.9

- script: 'pip install -r api/requirements.txt'
  displayName: 'Install Dependencies'

- task: Docker@2
  displayName: 'Log in to Azure Container Registry'
  inputs:
    containerRegistry: 'fyioai-svc'
    command: login

- task: Docker@2
  displayName: 'Build and Push API Docker Image'
  inputs:
    containerRegistry: 'fyioai-svc'
    Dockerfile: api/Dockerfile
    tags: '$(git rev-parse HEAD)'

- task: Docker@2
  displayName: 'Build and Push Web Docker Image'
  inputs:
    containerRegistry: 'fyioai-svc'
    Dockerfile: web/Dockerfile
    tags: '$(git rev-parse HEAD)'

- task: AzureCLI@2
  displayName: 'Deploy API'
  inputs:
    azureSubscription: 'rg-mvp-jpeast-svc'
    scriptType: batch
    scriptLocation: inlineScript
    inlineScript: |
     export GITHUB_SHA=$(git rev-parse HEAD)
     az containerapp update --name $(AZ_ACA_API) --resource-group $(AZ_RG) --image $(AZ_ACR_URL)/$(AZ_ACR_API):$(GITHUB_SHA)

- task: AzureCLI@2
  displayName: 'Deploy Web'
  inputs:
    azureSubscription: 'rg-mvp-jpeast-svc'
    scriptType: batch
    scriptLocation: inlineScript
    inlineScript: |
     export GITHUB_SHA=$(git rev-parse HEAD)
     az containerapp update --name $(AZ_ACA_WEB) --resource-group $(AZ_RG) --image $(AZ_ACR_URL)/$(AZ_ACR_WEB):$(GITHUB_SHA)
